// Code generated by "stringer -type=GameState -trimprefix GameState"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Handshaking-0]
	_ = x[Status-1]
	_ = x[Login-2]
	_ = x[Play-3]
}

const _GameState_name = "HandshakingStatusLoginPlay"

var _GameState_index = [...]uint8{0, 11, 17, 22, 26}

func (i GameState) String() string {
	if i < 0 || i >= GameState(len(_GameState_index)-1) {
		return "GameState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameState_name[_GameState_index[i]:_GameState_index[i+1]]
}
